FROM node:18 as builder

WORKDIR /usr/src

RUN git clone https://github.com/gear-tech/rosetta-api.git

RUN yarn install
RUN yarn build

FROM ubuntu:22.04
RUN apt update -y
RUN apt install wget curl vim xz-utils -y

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt install -y nodejs

RUN apt remove cmdtest -y
RUN apt remove yarn -y
RUN npm install -g yarn
RUN apt install supervisor -y

COPY --from=builder /usr/src /opt/rosetta-api

WORKDIR /opt/rosetta-api

# Download gear binary
RUN wget https://get.gear.rs/gear-nightly-linux-x86_64.tar.xz
RUN tar -xvf gear-nightly-linux-x86_64.tar.xz
RUN chmod +x gear
COPY supervisord-vara.conf /etc/supervisor/conf.d/supervisord.conf


EXPOSE 8080

CMD [ "/usr/bin/supervisord"]
