/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Rosetta);
  }
}(this, function(expect, Rosetta) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Rosetta.NetworkStatusResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NetworkStatusResponse', function() {
    it('should create an instance of NetworkStatusResponse', function() {
      // uncomment below and update the code to test NetworkStatusResponse
      //var instance = new Rosetta.NetworkStatusResponse();
      //expect(instance).to.be.a(Rosetta.NetworkStatusResponse);
    });

    it('should have the property currentBlockIdentifier (base name: "current_block_identifier")', function() {
      // uncomment below and update the code to test the property currentBlockIdentifier
      //var instance = new Rosetta.NetworkStatusResponse();
      //expect(instance).to.be();
    });

    it('should have the property currentBlockTimestamp (base name: "current_block_timestamp")', function() {
      // uncomment below and update the code to test the property currentBlockTimestamp
      //var instance = new Rosetta.NetworkStatusResponse();
      //expect(instance).to.be();
    });

    it('should have the property genesisBlockIdentifier (base name: "genesis_block_identifier")', function() {
      // uncomment below and update the code to test the property genesisBlockIdentifier
      //var instance = new Rosetta.NetworkStatusResponse();
      //expect(instance).to.be();
    });

    it('should have the property oldestBlockIdentifier (base name: "oldest_block_identifier")', function() {
      // uncomment below and update the code to test the property oldestBlockIdentifier
      //var instance = new Rosetta.NetworkStatusResponse();
      //expect(instance).to.be();
    });

    it('should have the property syncStatus (base name: "sync_status")', function() {
      // uncomment below and update the code to test the property syncStatus
      //var instance = new Rosetta.NetworkStatusResponse();
      //expect(instance).to.be();
    });

    it('should have the property peers (base name: "peers")', function() {
      // uncomment below and update the code to test the property peers
      //var instance = new Rosetta.NetworkStatusResponse();
      //expect(instance).to.be();
    });

  });

}));
