/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Rosetta);
  }
}(this, function(expect, Rosetta) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Rosetta.Operation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Operation', function() {
    it('should create an instance of Operation', function() {
      // uncomment below and update the code to test Operation
      //var instance = new Rosetta.Operation();
      //expect(instance).to.be.a(Rosetta.Operation);
    });

    it('should have the property operationIdentifier (base name: "operation_identifier")', function() {
      // uncomment below and update the code to test the property operationIdentifier
      //var instance = new Rosetta.Operation();
      //expect(instance).to.be();
    });

    it('should have the property relatedOperations (base name: "related_operations")', function() {
      // uncomment below and update the code to test the property relatedOperations
      //var instance = new Rosetta.Operation();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Rosetta.Operation();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new Rosetta.Operation();
      //expect(instance).to.be();
    });

    it('should have the property account (base name: "account")', function() {
      // uncomment below and update the code to test the property account
      //var instance = new Rosetta.Operation();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new Rosetta.Operation();
      //expect(instance).to.be();
    });

    it('should have the property coinChange (base name: "coin_change")', function() {
      // uncomment below and update the code to test the property coinChange
      //var instance = new Rosetta.Operation();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new Rosetta.Operation();
      //expect(instance).to.be();
    });

  });

}));
