/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Rosetta);
  }
}(this, function(expect, Rosetta) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Rosetta.Signature();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Signature', function() {
    it('should create an instance of Signature', function() {
      // uncomment below and update the code to test Signature
      //var instance = new Rosetta.Signature();
      //expect(instance).to.be.a(Rosetta.Signature);
    });

    it('should have the property signingPayload (base name: "signing_payload")', function() {
      // uncomment below and update the code to test the property signingPayload
      //var instance = new Rosetta.Signature();
      //expect(instance).to.be();
    });

    it('should have the property publicKey (base name: "public_key")', function() {
      // uncomment below and update the code to test the property publicKey
      //var instance = new Rosetta.Signature();
      //expect(instance).to.be();
    });

    it('should have the property signatureType (base name: "signature_type")', function() {
      // uncomment below and update the code to test the property signatureType
      //var instance = new Rosetta.Signature();
      //expect(instance).to.be();
    });

    it('should have the property hexBytes (base name: "hex_bytes")', function() {
      // uncomment below and update the code to test the property hexBytes
      //var instance = new Rosetta.Signature();
      //expect(instance).to.be();
    });

  });

}));
