/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Rosetta);
  }
}(this, function(expect, Rosetta) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Rosetta.ConstructionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConstructionApi', function() {
    describe('constructionCombine', function() {
      it('should call constructionCombine successfully', function(done) {
        //uncomment below and update the code to test constructionCombine
        //instance.constructionCombine(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('constructionDerive', function() {
      it('should call constructionDerive successfully', function(done) {
        //uncomment below and update the code to test constructionDerive
        //instance.constructionDerive(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('constructionHash', function() {
      it('should call constructionHash successfully', function(done) {
        //uncomment below and update the code to test constructionHash
        //instance.constructionHash(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('constructionMetadata', function() {
      it('should call constructionMetadata successfully', function(done) {
        //uncomment below and update the code to test constructionMetadata
        //instance.constructionMetadata(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('constructionParse', function() {
      it('should call constructionParse successfully', function(done) {
        //uncomment below and update the code to test constructionParse
        //instance.constructionParse(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('constructionPayloads', function() {
      it('should call constructionPayloads successfully', function(done) {
        //uncomment below and update the code to test constructionPayloads
        //instance.constructionPayloads(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('constructionPreprocess', function() {
      it('should call constructionPreprocess successfully', function(done) {
        //uncomment below and update the code to test constructionPreprocess
        //instance.constructionPreprocess(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('constructionSubmit', function() {
      it('should call constructionSubmit successfully', function(done) {
        //uncomment below and update the code to test constructionSubmit
        //instance.constructionSubmit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
