import { middleware } from 'express-openapi-validator';
import swaggerUI from 'swagger-ui-express';
import express, { Express } from 'express';
import cookieParser from 'cookie-parser';
import bodyParser from 'body-parser';
import jsYaml from 'js-yaml';
import cors from 'cors';
import http from 'http';
import path from 'path';
import fs from 'fs';

import logger from './logger';
import config from './config';

export default class ExpressServer {
  schema: any;
  app: Express;
  server: http.Server;

  constructor(private port: number, private openApiPath: string) {
    this.app = express();
    try {
      this.schema = jsYaml.load(fs.readFileSync(openApiPath));
    } catch (e) {
      logger.error('failed to start Express Server', e.message);
    }
    this.setupMiddleware();
  }

  setupMiddleware() {
    // this.setupAllowedMedia();
    this.app.use(cors());
    this.app.use(bodyParser.json({ limit: '14MB' }));
    this.app.use(express.json());
    this.app.use(express.urlencoded({ extended: false }));
    this.app.use(cookieParser());
    // Simple test to see that the server is up and responding
    this.app.get('/hello', (req, res) => res.send(`Hello World. path: ${this.openApiPath}`));
    // Send the openapi document *AS GENERATED BY THE GENERATOR*
    this.app.get('/openapi', (req, res) => res.sendFile(path.join(__dirname, 'api', 'openapi.yaml')));
    // View the openapi document in a visual interface. Should be able to test from this page
    this.app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(this.schema));
    this.app.get('/login-redirect', (req, res) => {
      res.status(200);
      res.json(req.query);
    });
    this.app.get('/oauth2-redirect.html', (req, res) => {
      res.status(200);
      res.json(req.query);
    });
  }

  launch() {
    this.app.use(
      middleware({
        apiSpec: this.openApiPath,
        operationHandlers: config.ROOT_DIR,
        fileUploader: { dest: config.FILE_UPLOAD_PATH },
        validateRequests: true,
      }),
    );

    this.app.use((err, req, res, next) => {
      console.log(err);
      res.status(err.status || 500).json({
        message: err.message || err,
        errors: err.errors || '',
      });
    });

    this.server = http.createServer(this.app).listen(this.port);
    logger.info(`Listening on port ${this.port}`);
  }

  async close() {
    if (this.server !== undefined) {
      await this.server.close();
      logger.info(`Server on port ${this.port} shut down`);
    }
  }
}
