name: 'CI'

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2

      - name: Install NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Download Gear node [release=build]
        run: wget -O ./gear https://github.com/gear-tech/gear/releases/download/build/gear

      - name: Build spec
        run: |
          chmod +x ./gear
          ./gear build-spec --dev > gear-spec-dev.json

      - name: Install rosetta-cli tool
        run: curl -sSfL https://raw.githubusercontent.com/coinbase/rosetta-cli/master/scripts/install.sh | sh -s
      
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build    

      - name: Update balances
        run: node ./test/set-prefunded-acc.js ./gear-spec-dev.json ./test/vara-development/config.json

      - name: Run Gear node
        run: nohup ./gear --chain ./gear-spec-dev.json --validator --alice --tmp --pruning archive --unsafe-ws-external --unsafe-rpc-external --rpc-methods Unsafe --rpc-cors all &

      - name: Make transfers
        run: node ./test/make-transfers.js

      - name: Update development config
        run: node ./util/cli/app.js update config/rosetta/vara-development.json -a http://127.0.0.1:9933

      - name: Run server in online mode
        run: yarn start:vara-development --update-config &

      - name: Run server in offline mode
        run: yarn start:offline --update-config &
        env:
          PORT: 8090

      - name: Run check:data
        run: ./bin/rosetta-cli --configuration-file ./test/vara-development/config.json check:data
      
      - name: Find out the balance of the prefunded account
        run: |
          curl -L 'http://127.0.0.1:8080/account/balance' -H 'Content-Type: application/json' -d '{"account_identifier": {"address": "kGkfymFqB4aBVunXCW69EzQRDtkZkUQB44GB4XJnwNwqmWyRN"},"network_identifier": {"blockchain": "vara","network": "development"}}'
      
      - name: Run check:construction
        run: ./bin/rosetta-cli --configuration-file ./test/development/config.json check:construction
