on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for release'
        required: true
      release_name:
        description: 'Release name'
        required: true        

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.release_name }}
          draft: false
          prerelease: false
